### PR TITLE
fix(#4095): Add Email notification for expired opc ua certificates

### LINKED ISSUE #4095: Send email notifications for expiring certificates
### Description

Add a feature that notifies administrators via email before certificates in the certificate storage expire.

The notification system should run as a scheduled cron job and send reminder emails based on configurable thresholds defined via environment variables.

### Requirements

* The system must send **email notifications to all admins** for certificates that are nearing expiration.
* A **single email** should include **all certificates expiring within the configured time window**.
* Email functionality must only be active when an email server is configured.

### Configuration

* **Enable & schedule job**

  * `SP_CERTIFICATE_EXPIRY_CRON`
  * Cron expression defining when the job runs
  * Default: runs once every night (e.g. `0 0 * * *`)

* **Reminder thresholds**

  * `SP_CERTIFICATE_EXPIRY_EMAIL_DAYS`
  * Comma-separated list of integers representing days before expiration when an email should be sent
  * Example:

    ```env
    SP_CERTIFICATE_EXPIRY_EMAIL_DAYS=30,14,7
    ```
  * If unset or empty, email reminders are disabled

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

### PR DESCRIPTION
**Pull request by tenthe**
This PR introduces a scheduled notification feature that informs administrators via email about certificates that are approaching expiration. A cron-based job periodically checks the certificate storage and sends a single aggregated reminder email to all admins, listing certificates that expire within configurable time windows.

The feature is fully configurable via environment variables, allowing both the schedule and reminder thresholds to be adjusted. 

**Configuration:**

* `SP_CERTIFICATE_EXPIRY_CRON` – Cron expression defining when the job runs (default: nightly).
* `SP_CERTIFICATE_EXPIRY_EMAIL_DAYS` – Comma-separated list of days before expiration to trigger reminders (e.g. `7,14,30`). If unset or empty, reminders are disabled.

### Remarks

PR introduces (a) breaking change(s): <yes/no>

PR introduces (a) deprecation(s): <yes/no>

### CODE REVIEW

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/scheduler/certificates/CertificateExpiryEmailScheduler.java [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ *
+ */
+
+/*
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/scheduler/certificates/CertificateExpiryEmailScheduler.java:1]: Duplicated license header

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/scheduler/DataLakeScheduler.java [hunk 2]
```diff
@@ -35,14 +35,15 @@
...
     private static final Logger LOG = LoggerFactory.getLogger(DataLakeExportManager.class);
 
     private final IDataExplorerSchemaManagement dataExplorerSchemaManagement = new DataExplorerDispatcher()
             .getDataExplorerManager()
             .getSchemaManagement();
 
     public void cleanupMeasurements() {
+        LOG.info("Retention CRON Job triggered.");
         List<DataLakeMeasure> allMeasurements = this.dataExplorerSchemaManagement.getAllMeasurements();
         LOG.info("GET ALL Measurements");
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/scheduler/DataLakeScheduler.java]:
```suggestion
        LOG.debug("GET ALL Measurements");
```

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/scheduler/DataLakeScheduler.java [hunk 3]
```diff
@@ -54,12 +55,12 @@ public void cleanupMeasurements() {
             }
 
         }
+        LOG.info("Retention CRON Job finished.");
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/scheduler/DataLakeScheduler.java:58]:
```suggestion
        LOG.debug("Retention CRON Job finished.");
```

**Review by dominikriemer — APPROVED** [review]
