### PR TITLE
fix(#2353): Add exception with detailed description for missing resources

### LINKED ISSUE #2353: NullPointer Exception when misconfiguring resource files for processing element
## Description

When a developer misconfigures the resource files for a processing element in StreamPipes, a `NullPointerException` is thrown during the generation of labels for the processing elements. This error occurs in the extensions service. The stack trace indicates that the issue originates in the `LabelGenerator` class of the `org.apache.streampipes.extensions.management.locales` package.

## Error Message
```
jakarta.servlet.ServletException: Request processing failed: java.lang.NullPointerException
...
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:112)
	at org.apache.streampipes.extensions.management.locales.LabelGenerator.makeProperties(LabelGenerator.java:131)
...
```

## Steps to Reproduce
- Misconfigure the resource files for a processing element (e.g. resource directory name does not match processor id)
- Trigger the generation of labels for the processing elements (e.g. go to http://localhost:8090/)

## Expected Behavior
The system should provide a meaningful error message for the developer to see why the labels could not be generated for a given processor.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

### PR DESCRIPTION
**Pull request by tenthe**
### Purpose

Fixes #2353.
The two API methods `.getElementTitle` & `.getElementDescription` of the `LabelGenerator` class have been provided with a check if the files exist.

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

File: streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/locales/LabelGeneratorTest.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+    assertEquals(expectedTitle, labelGenerator.getElementTitle());
+  }
+
+
+  private LabelGenerator getLabelGeneratorWithoutLocalesFile() {
+    var mockDescription = Mockito.mock(NamedStreamPipesEntity.class);
+    when(mockDescription.getAppId()).thenReturn(TEST_APP_ID);
+
+    var labelGenerator = new LabelGenerator(mockDescription);
+    var mockGenerator = spy(labelGenerator);
```
Comment (bossenti) [inline streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/locales/LabelGeneratorTest.java:77]: `mockedLabelGenerator` or `labelGeneratorMock`

**Review by bossenti — APPROVED** [review]
