### PR TITLE
Role Management for Assets in create Tasks

### LINKED ISSUE #3896: Role Management for Assets in create Tasks
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

UI

### What happened?

Currently, user roles are not considered when creating resources with asset links (e.g., Adapter).
The “Add to Asset” option should only be available to users with the Asset Admin role.  Restrict “Add to Asset” functionality so that it is visible and usable only for users with the Asset Admin role.

Affected Areas:

- Connect
- Pipeline
- Charts
- Dashboards

 Verify behavior across Connect, Pipeline, Charts, and Dashboards.
 Add or update Cypress nightly tests to validate this role-based restriction.

### How to reproduce?

_No response_

### Expected behavior

_No response_

### Additional technical information

_No response_

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by JHoelli**
### Purpose

Resolves #3896 . Option to add resources to Assets is now only available for Asset Admins. 

### Remarks
Further restricted access to "Persist Events" to the role PipelineAdmin. 

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

File: ui/src/app/dashboard/dialogs/edit-dashboard/edit-dashboard-dialog.component.ts [hunk 1]
```diff
@@ -70,6 +81,13 @@ export class EditDashboardDialogComponent implements OnInit {
         }
     }
 
+    hasRole(role: UserRole): boolean {
```
Comment (tenthe) [inline ui/src/app/dashboard/dialogs/edit-dashboard/edit-dashboard-dialog.component.ts]: Since we have this functionality in several locations, can we extract it into a utility method?

Comment (tenthe) [reply ui/src/app/dashboard/dialogs/edit-dashboard/edit-dashboard-dialog.component.ts]: Maybe we can include it into the `CurrentUserService`

File: ui/cypress/tests/userManagement/testUserRoleAsset.spec.ts [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+        ConnectUtils.addAdapter(
+            AdapterBuilder.create('Machine_Data_Simulator')
+                .setName('Machine Data Simulator Test 1')
+                .addInput('input', 'wait-time-ms', '1000')
+                .setStartAdapter(false)
+                .build(),
+        );
+        ConnectBtns.assetCheckbox().should('exist');
+
+        UserUtils.changeUserRole(newUser, UserRole.ROLE_ASSET_ADMIN);
```
Comment (tenthe) [inline ui/cypress/tests/userManagement/testUserRoleAsset.spec.ts]: Could you update the method’s signature—perhaps rename it to `toggleUserRole`, or split it into two separate methods like `addUserRole` and `removeUserRole`? At first, I thought the current method added the asset admin role, but it actually toggles it, correct?

File: ui/cypress/tests/userManagement/testUserRoleAsset.spec.ts [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+import { ConnectUtils } from '../../support/utils/connect/ConnectUtils';
+import { PipelineUtils } from '../../support/utils/pipeline/PipelineUtils';
+import { PipelineBtns } from '../../support/utils/pipeline/PipelineBtns';
+import { AssetUtils } from '../../support/utils/asset/AssetUtils';
+import { AdapterBuilder } from '../../support/builder/AdapterBuilder';
+import { DataExplorerUtils } from '../../support/utils/dataExplorer/DataExplorerUtils';
+import { DataExplorerBtns } from '../../support/utils/dataExplorer/DataExplorerBtns';
+import { ConnectBtns } from '../../support/utils/connect/ConnectBtns';
+
+describe('Test User Roles for Pipelines', () => {
```
Comment (tenthe) [inline ui/cypress/tests/userManagement/testUserRoleAsset.spec.ts:30]: Please provide an expressive name for the tests run in this test suite.

**Review by tenthe — CHANGES_REQUESTED** [review]

File: ui/cypress/tests/userManagement/testUserRoleAsset.spec.ts [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+    beforeEach('Setup Test', () => {
+        cy.initStreamPipesTest();
+
+        AssetUtils.goToAssets();
+        AssetUtils.addAndSaveAsset('Asset');
+    });
+
+    it('Connect Asset Role Check ', () => {
+        const newUser = UserUtils.createUser(
```
Comment (tenthe) [inline ui/cypress/tests/userManagement/testUserRoleAsset.spec.ts]: Can you initialize the user in the before each?
They always have the same roles, right?

**Review by tenthe — APPROVED** [review]
