### PR TITLE
fix(3887): permission objects lost after exporting and re importing assets with sanitized resource ids

### LINKED ISSUE #3887: Permission objects lost after exporting and re-importing assets with sanitized resource IDs
### Body

When exporting an asset containing resources and importing it into another StreamPipes instance, some resources may lose their associated permission objects. During export, the IDs of `Dashboards`, `DataExplorerWidgets` and `DataStreams` are sanitized. Since these IDs are referenced in the permission objects, this causes a mismatch between the actual resource ID and the permission object ID after import.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

### PR DESCRIPTION
**Pull request by tenthe**
### Purpose
This PR addresses the loss of permission objects when importing assets with sanitized resource IDs.

The fix includes two parts:

1. A migration script that restores missing permission objects in already affected installations.
2. An update to the import logic to ensure the original resource ID is used in permission objects, preventing future mismatches.

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+
+  @Override
+  public void executeMigration() throws IOException {
+    migrateDashboardPermissions();
+    migrateChartsPermissions();
+    migrateDataStreamPermissions();
+  }
+
+  private void migrateDashboardPermissions() {
+    LOG.info("Strart migrate permissions for dashboards");
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java]:
```suggestion
    LOG.info("Start migrate permissions for dashboards");
```

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+    var dataExplorerDashboardStorage = StorageDispatcher.INSTANCE
+        .getNoSqlStore()
+        .getDataExplorerDashboardStorage();
+    var dashboards = dataExplorerDashboardStorage.findAll();
+    migrateResourcePermissions(dashboards);
+    LOG.info("Finished migrate permissions for dashboards");
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java]: maybe this can also be log level debug

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+  }
+
+  private void migrateChartsPermissions() {
+    LOG.info("Strart migrate permissions for charts");
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java]:
```suggestion
    LOG.info("Start migrate permissions for charts");
```

File: streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+    var dataExplorerWidgetStorage = StorageDispatcher.INSTANCE
+        .getNoSqlStore()
+        .getDataExplorerWidgetStorage();
+    var charts = dataExplorerWidgetStorage.findAll();
+    migrateResourcePermissions(charts);
+    LOG.info("Finished migrate permissions for charts");
+  }
+
+  private void migrateDataStreamPermissions() {
+    LOG.info("Strart migrate permissions for data streams");
```
Comment (dominikriemer) [inline streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v0980/FixImportedPermissionsMigration.java]:
```suggestion
    LOG.info("Start migrate permissions for data streams");
```

**Review by dominikriemer — APPROVED** [review]
